version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "4000:4000"
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./client/build:/usr/share/nginx/html:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
